name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  test-and-lint:
    env:
      SECRET: ${{ secrets.SECRET }}
      TEST_MONGODB_URI:  ${{ secrets.TEST_MONGODB_URI }}
      MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Run backend tests
        run: npm run test
      - name: build
        run: npm run build
      - name: run frontend tests
        run: npm run test:front
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Debug env
        run: node -e "console.log(process.env.MONGODB_URI)"
      - name: Run Playwright tests
        run: npm run test:e2e